name: Setup Workspace
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft

    - name: Configure Google Services File
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json