version: '3.7'
services:
  build_android:
    image: alvrme/alpine-android:android-29-jdk11-v2021.03.17
    user: root
    volumes:
      - ./:/source
    working_dir: /source
    environment:
      - UPLOAD_AWS_ACCESS_KEY_ID=${UPLOAD_AWS_ACCESS_KEY_ID}
      - UPLOAD_AWS_SECRET_ACCESS_KEY=${UPLOAD_AWS_SECRET_ACCESS_KEY}
      - STORE_PASSWORD=${STORE_PASSWORD}
      - KEY_ALIAS=${KEY_ALIAS}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - BUILDKITE_BUILD_NUMBER=${BUILDKITE_BUILD_NUMBER}
      - BUILDKITE_BRANCH=${BUILDKITE_BRANCH}
      - BUILDKITE_MESSAGE=${BUILDKITE_MESSAGE}
