#checkov:skip=CKV_OPENAPI_4:Not required to have auth schema defs
openapi: 3.0.0
info:
  title: "Rokt Android Demo app"
  x-cortex-tag: "native-demo-android"
  x-cortex-type: service
  description: |
    Android native app to demonstrate and test Rokt SDK capabilities.
  x-cortex-git:
    github:
      repository: "ROKT/rokt-demo-android"

  x-cortex-owners:
    - type: group
      name: "new-integrations"
      provider: CORTEX
  x-cortex-groups:
    - "lang-kotlin"

  x-cortex-oncall:
    opsgenie:
      type: SCHEDULE
      id: "Mobile Integrations_schedule"

  x-cortex-link:
    - name: Mobile SDK Detailed Error View
      type: dashboard
      url: https://rokt.datadoghq.com/dashboard/nsi-c8c-gtd
