name: Setup Java
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        java-version: 17
        distribution: microsoft