# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build Android Demo"
  lane :buildAndKtlint do
    # Build android flavours and unit test
    gradle(task: "assembleDebug")
    gradle(task: "ktlintCheck")
  end

  desc "Deploy a beta version to the Google Play"
  lane :beta do
#     gradle(task: "clean bundleRelease")
    gradle(
          task: 'assembleRelease',
          build_type: 'Release'
        )
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :production do
    gradle(task: "clean bundleRelease")
    upload_to_play_store
  end

end
