name: Run tests and lint

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Workspace
        uses: ./.github/actions/setup-workspace

      - name: Run lint
        run: ./gradlew ktlintCheck

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Workspace
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: ./gradlew test

  assemble-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Workspace
        uses: ./.github/actions/setup-workspace

      - name: Assemble Debug
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk