name: Run tests and lint

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: ./.github/actions/setup-java

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run lint
        run: ./gradlew ktlintCheck

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: ./.github/actions/setup-java

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure Google Services File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json

      - name: Run tests
        run: ./gradlew test

  assemble-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: ./.github/actions/setup-java

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure Google Services File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json

      - name: Assemble Debug
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk