name: Trigger Snapshot build to Firebase

on:
  repository_dispatch:
    types:
      - snapshot-build

permissions:
  id-token: write
  contents: read

env:
  VERSION_NAME: ${{ github.event.client_payload.version_name }}
  RELEASE_NOTES: ${{ github.event.client_payload.release_notes }}

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Update version
        run: |
          echo "Updating version name to $VERSION_NAME"
          sed -i "s/version_name=.*/version_name=$VERSION_NAME/" gradle.properties
          cat gradle.properties
          echo "Updating ROKT SDK version"
          sed -i "s/rokt = .*/rokt = \"com.rokt:roktsdk:${VERSION_NAME}\"/" buildSrc/src/main/java/dependencies.kt
          cat buildSrc/src/main/java/dependencies.kt

      - name: Build APK
        uses: ./.github/actions/build-apk
        with:
          store_password: ${{ secrets.ANDROID_STORE_PASSWORD }}
          key_alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          key_password: ${{ secrets.ANDROID_KEY_PASSWORD }}
          google_services_json: ${{ secrets.GOOGLE_SERVICES_JSON }}
          keystore_file: ${{ secrets.ANDROID_KEYSTORE_FILE }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

  publish-build-to-firebase:
    runs-on: ubuntu-latest
    needs: build-apk

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download APK artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: release-apk
          path: .

      - name: Upload APK
        uses: ./.github/actions/upload-apk
        with:
          apk_path: app-release.apk
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          firebase_app_id: ${{ secrets.FIREBASE_APP_ID }}
          testing_groups: ${{ secrets.SNAPSHOT_TESTING_GROUPS }}
          release_notes: ${{ env.RELEASE_NOTES }}
